export const Constant = {
    title: "Fiber",
    titleLogin: "Create Your Fiber account",
    titleChecked: " By creating an account an Fiber,you agree to",
    titleButton: " Create Fiber Account ",
    Already : "Already have aon account?",
    unParallel : "Unparalleled Template",
    description : "Crafted by A team of Professional designer, our",
    description2 : "template are Unparalleled in the market",
    fiber : "Fiber",
    signIn: 'sign In',
    signUp: 'sign Up',
    TitleStar: 'Rated 4.8/5 (243 reviews)',
    community : "Community",
    pricing : "Pricing",
    feature : "Feature",
    term: "Term and Condition",
    createPortfolio: "Create your portfolio in minutes.",
    FilberDesc: "with Fiber, you can setup your own personal portfolio in minutes with dozens of premade, beautiful template",
    view : "View Examples",
    btnTitle : "Start Free Trial",
    credit: "No Credit Card Required ",
    template: " 10 Free Templates",
    whyFiber: " why Fiber ?",
    goodPortfolio1: " A good portfolio means good ",
    goodPortfolio2: "employability.",
    diversify: "Diversify your portfolio.",
    diversifyDec:" Create on even more impressive portfolio by creating case studies for your project simply portfolio by creating case ",
    diversifyDec2:" follow our step by step guide",
    viewMathew:" View Mathew Portfolio",
    sitemap:" Sitemap",
    resources:" Resources",
    company:" Company",
    portfolios:" Portfolios",
}